ALLDIR = "https://cyder.oregonstate.edu/api/v1/"
CORE_CENTER = "https://cyder.oregonstate.edu/api/v1/core/system/"
CORE_SYSTEM = "https://cyder.oregonstate.edu/api/v1/core/system/"
CORE_SYSTEM_ATTRIBUTES = "https://cyder.oregonstate.edu/api/v1/core/system/attributes/"
CORE_USER = 'https://cyder.nws.oregonstate.edu/api/v1/core/user/'
DYNAMIC_INTERFACE = "https://cyder.oregonstate.edu/api/v1/dhcp/dynamic_interface/"
DYNAMIC_INTERFACE_ATTRIBUTES = "https://cyder.oregonstate.edu/api/v1/dhcp/dynamic_interface/attributes/" #returns 404.
NETWORK = "https://cyder.oregonstate.edu/api/v1/dhcp/network/"
NETWORK_ATTRIBUTES = "https://cyder.oregonstate.edu/api/v1/dhcp/network/attributes/"
DHCP_RANGE = "https://cyder.oregonstate.edu/api/v1/dhcp/range/"
DHCP_RANGE_ATTRIBUTES = "https://cyder.oregonstate.edu/api/v1/dhcp/range/attributes/"
SITE = "https://cyder.oregonstate.edu/api/v1/dhcp/site/"
SITE_ATTRIBUTES = "https://cyder.oregonstate.edu/api/v1/dhcp/site/attributes/"
STATIC_INTERFACE = "https://cyder.oregonstate.edu/api/v1/dhcp/static_interface/" #contains all static interfaces, including multiple entries for systems with multiple entries. Does not display attributes, does display IP, MAC, Domain etc.
STATIC_INTERFACE_ATTRIBUTES = "https://cyder.oregonstate.edu/api/v1/dhcp/static_interface/attributes/" #returns 404
VLAN = "https://cyder.oregonstate.edu/api/v1/dhcp/vlan/"
VLAN_ATTRIBUTES = "https://cyder.oregonstate.edu/api/v1/dhcp/vlan/attributes/"
VRF = "https://cyder.oregonstate.edu/api/v1/dhcp/vrf/"
VRF_ATTRIBUTES = "https://cyder.oregonstate.edu/api/v1/dhcp/vrf/attributes/"
WORKGROUP = "https://cyder.oregonstate.edu/api/v1/dhcp/workgroup/"
WORKGROUP_ATTRIBUTES = "https://cyder.oregonstate.edu/api/v1/dhcp/workgroup/attributes/"
ADDRESS_RECORD = "https://cyder.oregonstate.edu/api/v1/dns/address_record/"
CNAME = 'https://cyder.oregonstate.edu/api/v1/dns/cname/' #only contains cname. Guide on cyder API found: https://cyder.oregonstate.edu/docs/api/intro_python/index.html#. Uses cname for examples.
DOMAIN = "https://cyder.oregonstate.edu/api/v1/dns/domain/"
MX = "https://cyder.oregonstate.edu/api/v1/dns/mx/"
NAMESERVER = 'https://cyder.oregonstate.edu/api/v1/dns/nameserver/'
PTR = "https://cyder.oregonstate.edu/api/v1/dns/ptr/"
SOA = "https://cyder.oregonstate.edu/api/v1/dns/soa/"
SOA_ATTRIBUTES = "https://cyder.oregonstate.edu/api/v1/dns/soa/attributes/"
SRV = "https://cyder.oregonstate.edu/api/v1/dns/srv/"
SSHFP = "https://cyder.oregonstate.edu/api/v1/dns/sshfp/"
DNS_TXT = "https://cyder.oregonstate.edu/api/v1/dns/txt/"