version: '3.8'

services:
  backend:
    build:
      context: ./back_end
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./front_end
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
